feature: add community documentations
chaosblade-io/chaosblade-website pull request #50
Opened 2022-07-18 06:35 UTC by Icesource

Signed-off-by: Icesource <gonghuajian.ghj@alibaba-inc.com>

补充社区文档
* PR提交指南
* 开发规范
* Issue提交和处理规范

2022-07-18 06:41 UTC, sunny0826 requested changes
可以在 Review 页面查看效果

2022-07-18 06:41 UTC, sunny0826 commented on docs/community/contributor-overview.md
> +---
需要添加一些内容，Review 页面：https://deploy-preview-50--chaosblade.netlify.app/docs/community/contributor-overview

2022-07-18 06:41 UTC, sunny0826 commented on docs/community/dev-environment.md
> +---
同上

2022-07-18 07:05 UTC, sunny0826 commented on sidebars.js
> +        "community/dev-environment",
如果 dev-environment 和 overview 是 TBD 状态的话，可以先不要在 这里添加 item，等补充完全内容后，在添加 item

2022-07-19 06:13 UTC, sunny0826 approved these changes
LGTM

2022-07-19 06:13 UTC, merged

2022-07-19 06:14 UTC, Icesource commented on sidebars.js
> +        "community/dev-environment",
done，感谢你的Review @sunny0826